### ISSUE TITLE
Auto-Login Feature from Plesk

### ISSUE THREAD

**Issue by FSProgramming-de** [dwwe2017/teamspeak-interface#2]
Hello, 

Is there also Auto Login for the panel as in the Plesk Demo for the superadmin? 

Unfortunately I have not found anything in the wiki. 

Thanks in advance

With kind regards
Dominik

**Comment by dwwe2017** [comment]
Hello Dominik, 
first of all thank you for your question. The auto-login feature can only be used in conjunction with the Plesk extension. You have probably noticed that the extension is currently very outdated. We are currently working on a new version of the Plesk extension, but the migration is very complex because we have changed almost everything from version 1.3 of the TSI. But I am working on it.

Best regards,
Daniel
